import { useCallback, useEffect, useMemo, useState } from "react";
import { MapCanvas } from "@/components/non_prebuilt/MapCanvas.jsx";
import { MapInfoPanel } from "@/components/non_prebuilt/MapInfoPanel.jsx";
import { mapApi } from "@/services/mapApi.js";
import { buildProfileIndex } from "@/lib/map/profileUtils.js";
import "@/styles/map.css";
import { Button } from "@/components/ui/button";
import { useNavigate } from "react-router-dom";

export default function DashboardHome() {
  const [status, setStatus] = useState("Loading map…");
  const [selection, setSelection] = useState(null);
  const [profilesByDguid, setProfilesByDguid] = useState(new Map());
  const [isFullscreen, setIsFullscreen] = useState(false);

  useEffect(() => {
    let isMounted = true;

    mapApi
      .getDaProfiles()
      .then((payload) => {
        if (!isMounted) return;
        const { index } = buildProfileIndex(payload);
        setProfilesByDguid(index);
      })
      .catch((error) => {
        console.error("[DashboardHome]", error);
        if (isMounted) {
          setStatus(`Error: ${error.message}`);
        }
      });

    return () => {
      isMounted = false;
    };
  }, []);

  useEffect(() => {
    if (!isFullscreen) return undefined;

    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";

    function handleKeyDown(event) {
      if (event.key === "Escape") {
        setIsFullscreen(false);
      }
    }

    window.addEventListener("keydown", handleKeyDown);

    return () => {
      document.body.style.overflow = previousOverflow;
      window.removeEventListener("keydown", handleKeyDown);
    };
  }, [isFullscreen]);

  const handleDaSelect = useCallback((dguid) => {
    setSelection({ type: "da", dguid });
  }, []);

  const handleFedSelect = useCallback((fedNum, fedName) => {
    setSelection({ type: "fed", fedNum, fedName });
  }, []);

  const handleStatusChange = useCallback((message) => {
    setStatus(message);
  }, []);

  const handleToggleFullscreen = useCallback(() => {
    setIsFullscreen((current) => !current);
  }, []);

  const panelSelection = useMemo(() => selection, [selection]);

  const navigate = useNavigate();

  return (
    <div className="flex flex-col gap-2">
      <div className="w-full flex justify-center bg-white py-10 ">
        <h1 className="text-5xl font-bold text-primary">
          Dashboard Home
        </h1>
      </div>
      <div className="px-15">
        <div className="flex gap-2">
          <Button onClick={() => navigate(-1)}>
            Back
          </Button>
          <Button onClick={() => navigate("/dashboard/graphs")}>
            Graphs and Stats
          </Button>
          <Button onClick={() => navigate("/dashboard/submissionsTable")}>
            All Submissions
          </Button>
        </div>
        {/* styling for total submissions counter generated by AI*/}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mt-4">
          <div className="bg-white border rounded-lg p-4 text-center shadow-sm">
            <p className="text-sm text-muted-foreground">
              Total Submissions
            </p>
            <p className="text-4xl font-bold text-primary">
              128
            </p>
          </div>
        </div>
        <div className="space-y-2">
          <p className="text-sm text-muted-foreground">Support vs Oppose</p>

          {/* styling for supporting vs opposing bar generated by AI*/}
          <div className="w-full h-3 bg-muted rounded-full overflow-hidden flex">
            <div
              className="bg-green-500"
              style={{ width: "68%" }}
            />
            <div
              className="bg-red-500"
              style={{ width: "32%" }}
            />
          </div>

          <div className="flex justify-between text-xs text-muted-foreground">
            <span>Support: 68%</span>
            <span>Oppose: 32%</span>
          </div>
        </div>
        <div
          className={`map-dashboard${isFullscreen ? " map-dashboard--fullscreen" : ""}`}
        >
          <section className="map-dashboard__main" aria-label="Map workspace">
            {!isFullscreen ? (
              <div className="map-dashboard__spacer" aria-hidden="true" />
            ) : null}
            <div className="map-dashboard__map-wrap">
              <div className="map-dashboard__status" aria-live="polite">
                {status}
              </div>
              <MapCanvas
                isFullscreen={isFullscreen}
                onDaSelect={handleDaSelect}
                onFedSelect={handleFedSelect}
                onStatusChange={handleStatusChange}
                onToggleFullscreen={handleToggleFullscreen}
              />
            </div>
          </section>

          <MapInfoPanel selection={panelSelection} profilesByDguid={profilesByDguid} />
        </div>
      </div>
    </div>
  );
}
