#!/usr/bin/env python3
"""Generate FED and place label GeoJSON for map-mvp Step 4.

Data sources (priority order for place names):
  1. Local bundle CSVs under scripts/data/bundle/ (schema-aligned paths)
     - profile_2021/006_dissemination_areas/territories_geo_index.csv
     - profile_2021/016_028_province_csds/*_geo_index.csv
     - profile_2021/raw/**/**_English_CSV_data.csv  (GEO_NAME + DGUID)
  2. Coordinate reference: scripts/data/yukon_places.json (read-only, not overwritten)
  3. DA centroids from map-mvp/data/single_fed_das.geojson (for profile CSV join)

FED names: scripts/data/fed_names_2023.json (read-only, not overwritten).

Does NOT call external APIs. Re-run after dropping CSVs into scripts/data/bundle/.
"""

from __future__ import annotations

import csv
import io
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "map-mvp" / "data"
CACHE_DIR = Path(__file__).resolve().parent / "data"
BUNDLE_DIR = CACHE_DIR / "bundle"

FED_GEOJSON = DATA_DIR / "fed_boundaries_2023.geojson"
DA_GEOJSON = DATA_DIR / "single_fed_das.geojson"
FED_NAMES_REF = CACHE_DIR / "fed_names_2023.json"
YUKON_PLACES_REF = CACHE_DIR / "yukon_places.json"

FED_LABELS_OUT = DATA_DIR / "fed_labels.geojson"
PLACE_LABELS_YT_OUT = DATA_DIR / "place_labels_yt.geojson"
PLACE_LABELS_CSD_OUT = DATA_DIR / "place_labels_csd.geojson"

TERRITORIES_GEO_INDEX = (
    BUNDLE_DIR / "profile_2021" / "006_dissemination_areas" / "territories_geo_index.csv"
)
GEO_INDEX_GLOB = "profile_2021/016_028_province_csds/*_geo_index.csv"
PROFILE_CSV_GLOB = "profile_2021/raw/**/*_English_CSV_data.csv"


# ---------------------------------------------------------------------------
# Geometry helpers (pure Python — no geopandas)
# ---------------------------------------------------------------------------


def ring_centroid(ring: list[list[float]]) -> tuple[float, float]:
    if len(ring) < 3:
        lng = sum(p[0] for p in ring) / len(ring)
        lat = sum(p[1] for p in ring) / len(ring)
        return lng, lat

    area = 0.0
    cx = 0.0
    cy = 0.0
    for i, point in enumerate(ring):
        nxt = ring[(i + 1) % len(ring)]
        cross = point[0] * nxt[1] - nxt[0] * point[1]
        area += cross
        cx += (point[0] + nxt[0]) * cross
        cy += (point[1] + nxt[1]) * cross

    area *= 0.5
    if abs(area) < 1e-12:
        lng = sum(p[0] for p in ring) / len(ring)
        lat = sum(p[1] for p in ring) / len(ring)
        return lng, lat

    return cx / (6.0 * area), cy / (6.0 * area)


def polygon_centroid(coords: list) -> tuple[float, float]:
    if not coords:
        return 0.0, 0.0

    best_area = 0.0
    best_centroid = ring_centroid(coords[0])
    for ring in coords:
        xs = [p[0] for p in ring]
        ys = [p[1] for p in ring]
        area = abs((max(xs) - min(xs)) * (max(ys) - min(ys)))
        if area >= best_area:
            best_area = area
            best_centroid = ring_centroid(ring)
    return best_centroid


def geometry_centroid(geometry: dict) -> tuple[float, float]:
    geom_type = geometry["type"]
    coords = geometry["coordinates"]

    if geom_type == "Polygon":
        return polygon_centroid(coords)
    if geom_type == "MultiPolygon":
        largest = coords[0]
        largest_area = 0.0
        for polygon in coords:
            ring = polygon[0]
            xs = [p[0] for p in ring]
            ys = [p[1] for p in ring]
            area = abs((max(xs) - min(xs)) * (max(ys) - min(ys)))
            if area > largest_area:
                largest_area = area
                largest = polygon
        return polygon_centroid(largest)
    if geom_type == "Point":
        return coords[0], coords[1]
    return 0.0, 0.0


# ---------------------------------------------------------------------------
# Reference data (read-only)
# ---------------------------------------------------------------------------


def load_fed_names() -> dict[str, str]:
    if not FED_NAMES_REF.exists():
        raise SystemExit(
            f"Missing FED name reference: {FED_NAMES_REF}\n"
            "This file is maintained separately and is not regenerated by this script."
        )
    return json.loads(FED_NAMES_REF.read_text(encoding="utf-8"))


def load_yukon_coord_reference() -> tuple[dict[str, dict], dict[str, dict]]:
    """Index yukon_places.json by geo_code and lower-case name (read-only)."""
    by_code: dict[str, dict] = {}
    by_name: dict[str, dict] = {}

    if not YUKON_PLACES_REF.exists():
        return by_code, by_name

    for row in json.loads(YUKON_PLACES_REF.read_text(encoding="utf-8")):
        code = normalize_geo_code(row.get("geo_code", ""))
        name = str(row.get("name", "")).strip()
        if code:
            by_code[code] = row
        if name:
            by_name[name.lower()] = row

    return by_code, by_name


def normalize_geo_code(value: object) -> str:
    text = str(value).strip()
    if not text or text.lower() == "nan":
        return ""
    if "." in text:
        text = text.split(".", 1)[0]
    return text


# ---------------------------------------------------------------------------
# Bundle CSV readers
# ---------------------------------------------------------------------------


# StatCan / Elections Canada CSVs are often UTF-8 but may be cp1252 (French accents).
CSV_ENCODINGS = ("utf-8-sig", "utf-8", "cp1252", "latin-1")


def read_csv_dict_rows(path: Path) -> list[dict[str, str]]:
    raw = path.read_bytes()
    last_error: Exception | None = None
    for encoding in CSV_ENCODINGS:
        try:
            text = raw.decode(encoding)
            return list(csv.DictReader(io.StringIO(text)))
        except UnicodeDecodeError as error:
            last_error = error
    if last_error:
        raise last_error
    text = raw.decode(CSV_ENCODINGS[0])
    return list(csv.DictReader(text.splitlines()))


def read_geo_index_csv(path: Path) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for row in read_csv_dict_rows(path):
        code = normalize_geo_code(
            row.get("Geo Code") or row.get("GEO_CODE") or row.get("geo_code") or ""
        )
        name = str(
            row.get("Geo Name") or row.get("GEO_NAME") or row.get("geo_name") or ""
        ).strip()
        if code and name:
            rows.append({"geo_code": code, "name": name})
    return rows


def discover_profile_csvs() -> list[Path]:
    base = BUNDLE_DIR / "profile_2021" / "raw"
    if not base.exists():
        return []
    return sorted(base.rglob("*_English_CSV_data.csv"))


def read_profile_geo_names(path: Path) -> dict[str, str]:
    """DGUID -> GEO_NAME from long-format profile CSV (one row per characteristic)."""
    names: dict[str, str] = {}
    for row in read_csv_dict_rows(path):
        char_id = str(row.get("CHARACTERISTIC_ID", "")).strip()
        if char_id and char_id != "1":
            continue
        dguid = str(row.get("DGUID", "")).strip()
        geo_name = str(row.get("GEO_NAME", "")).strip()
        if dguid and geo_name:
            names[dguid] = geo_name
    return names


def load_da_centroids() -> dict[str, tuple[float, float, str]]:
    """DGUID -> (lng, lat, label_hint) from single_fed_das.geojson."""
    if not DA_GEOJSON.exists():
        return {}

    geojson = json.loads(DA_GEOJSON.read_text(encoding="utf-8"))
    centroids: dict[str, tuple[float, float, str]] = {}
    for feature in geojson.get("features", []):
        dguid = str(feature.get("properties", {}).get("DGUID", "")).strip()
        if not dguid:
            continue
        lng, lat = geometry_centroid(feature["geometry"])
        centroids[dguid] = (lng, lat, dguid)
    return centroids


def resolve_coord(
    geo_code: str,
    name: str,
    by_code: dict[str, dict],
    by_name: dict[str, dict],
) -> tuple[float, float] | None:
    code = normalize_geo_code(geo_code)
    if code and code in by_code:
        row = by_code[code]
        return row["lng"], row["lat"]

    key = name.lower()
    if key in by_name:
        row = by_name[key]
        return row["lng"], row["lat"]

    return None


def place_feature(
    name: str,
    lng: float,
    lat: float,
    geo_code: str = "",
    source: str = "",
) -> dict:
    props: dict[str, str] = {"name": name}
    if geo_code:
        props["geo_code"] = geo_code
    if source:
        props["source"] = source
    return {
        "type": "Feature",
        "geometry": {"type": "Point", "coordinates": [lng, lat]},
        "properties": props,
    }


def dedupe_features(features: list[dict]) -> list[dict]:
    seen: set[str] = set()
    out: list[dict] = []
    for feature in features:
        name = feature["properties"]["name"].lower()
        if name in seen:
            continue
        seen.add(name)
        out.append(feature)
    out.sort(key=lambda f: f["properties"]["name"])
    return out


# ---------------------------------------------------------------------------
# Label builders
# ---------------------------------------------------------------------------


def build_fed_labels() -> dict:
    fed_geojson = json.loads(FED_GEOJSON.read_text(encoding="utf-8"))
    fed_names = load_fed_names()
    features = []

    for feature in fed_geojson.get("features", []):
        fed_num = str(feature.get("properties", {}).get("fed_num", "")).strip()
        if not fed_num:
            continue
        lng, lat = geometry_centroid(feature["geometry"])
        features.append(
            place_feature(
                fed_names.get(fed_num, f"FED {fed_num}"),
                lng,
                lat,
                geo_code=fed_num,
                source="fed_boundaries_2023.geojson+fed_names_2023.json",
            )
        )

    features.sort(key=lambda f: f["properties"]["geo_code"])
    return {"type": "FeatureCollection", "features": features}


def build_place_labels_yt() -> tuple[dict, list[str]]:
    """Yukon / territories place labels for map-mvp."""
    log: list[str] = []
    features: list[dict] = []
    by_code, by_name = load_yukon_coord_reference()

    if TERRITORIES_GEO_INDEX.exists():
        rows = read_geo_index_csv(TERRITORIES_GEO_INDEX)
        log.append(f"Read {len(rows)} rows from {TERRITORIES_GEO_INDEX.name}")
        for row in rows:
            coord = resolve_coord(row["geo_code"], row["name"], by_code, by_name)
            if coord:
                lng, lat = coord
                features.append(
                    place_feature(
                        row["name"],
                        lng,
                        lat,
                        geo_code=row["geo_code"],
                        source="territories_geo_index.csv",
                    )
                )
            else:
                log.append(f"  [skip] no coordinates for {row['name']} ({row['geo_code']})")

    profile_names: dict[str, str] = {}
    for csv_path in discover_profile_csvs():
        names = read_profile_geo_names(csv_path)
        profile_names.update(names)
        log.append(f"Read {len(names)} GEO_NAME rows from {csv_path.relative_to(BUNDLE_DIR)}")

    if profile_names:
        da_centroids = load_da_centroids()
        matched = 0
        for dguid, geo_name in profile_names.items():
            if dguid not in da_centroids:
                continue
            lng, lat, _ = da_centroids[dguid]
            features.append(
                place_feature(
                    geo_name,
                    lng,
                    lat,
                    geo_code=dguid,
                    source="profile_csv+single_fed_das.geojson",
                )
            )
            matched += 1
        log.append(f"Joined {matched} DA-level labels from profile CSV + DA centroids")

    if not features and YUKON_PLACES_REF.exists():
        log.append(f"Fallback: using coordinate reference {YUKON_PLACES_REF.name}")
        for row in json.loads(YUKON_PLACES_REF.read_text(encoding="utf-8")):
            features.append(
                place_feature(
                    row["name"],
                    row["lng"],
                    row["lat"],
                    geo_code=str(row.get("geo_code", "")),
                    source="yukon_places.json",
                )
            )

    features = dedupe_features(features)
    if not features:
        log.append(
            "No Yukon place labels produced. Add CSVs under scripts/data/bundle/ "
            "or ensure scripts/data/yukon_places.json exists."
        )

    return {"type": "FeatureCollection", "features": features}, log


def build_place_labels_csd() -> tuple[dict, list[str]]:
    """Province CSD name indexes from 016_028 (optional national layer)."""
    log: list[str] = []
    features: list[dict] = []
    by_code, by_name = load_yukon_coord_reference()

    for path in sorted(BUNDLE_DIR.glob(GEO_INDEX_GLOB)):
        prov = path.stem.replace("_geo_index", "")
        rows = read_geo_index_csv(path)
        log.append(f"Read {len(rows)} rows from {path.name}")
        for row in rows:
            coord = resolve_coord(row["geo_code"], row["name"], by_code, by_name)
            if not coord:
                continue
            lng, lat = coord
            features.append(
                place_feature(
                    row["name"],
                    lng,
                    lat,
                    geo_code=row["geo_code"],
                    source=f"016_028/{path.name}",
                )
            )
        if not features:
            log.append(
                f"  [note] {prov}: names only — no coordinates until CSD boundaries "
                "or a coord lookup table is added"
            )

    features = dedupe_features(features)
    return {"type": "FeatureCollection", "features": features}, log


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    if not FED_GEOJSON.exists():
        raise SystemExit(f"Missing FED GeoJSON: {FED_GEOJSON}")

    print(f"Bundle CSV root: {BUNDLE_DIR}")
    print("Reference files (read-only):", FED_NAMES_REF.name, YUKON_PLACES_REF.name)
    print()

    fed_labels = build_fed_labels()
    place_yt, yt_log = build_place_labels_yt()
    place_csd, csd_log = build_place_labels_csd()

    FED_LABELS_OUT.write_text(json.dumps(fed_labels, ensure_ascii=False), encoding="utf-8")
    PLACE_LABELS_YT_OUT.write_text(json.dumps(place_yt, ensure_ascii=False), encoding="utf-8")
    if place_csd["features"]:
        PLACE_LABELS_CSD_OUT.write_text(
            json.dumps(place_csd, ensure_ascii=False), encoding="utf-8"
        )

    print(f"Wrote {len(fed_labels['features'])} FED labels -> {FED_LABELS_OUT}")
    print(f"Wrote {len(place_yt['features'])} Yukon place labels -> {PLACE_LABELS_YT_OUT}")
    if place_csd["features"]:
        print(f"Wrote {len(place_csd['features'])} CSD labels -> {PLACE_LABELS_CSD_OUT}")

    print("\n--- Yukon label pipeline ---")
    for line in yt_log:
        print(line)

    if csd_log:
        print("\n--- 016_028 CSD index ---")
        for line in csd_log:
            print(line)

    if not TERRITORIES_GEO_INDEX.exists():
        print(
            f"\nTip: drop territories_geo_index.csv at:\n  {TERRITORIES_GEO_INDEX}\n"
            "then re-run this script."
        )


if __name__ == "__main__":
    main()
